dist: bionic
language: perl
os: linux
branches:
  only:
  - master
cache:
  directories:
  - perl_modules
before_install:
- cpanm local::lib
- eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
- cpanm --notest Dist::Zilla
- eval "cpanm --notest Sys::CpuLoadX || exit 0"
- git clone https://github.com/sanger-pathogens/assembly_improvement
- cd assembly_improvement
- dzil authordeps --missing | cpanm --notest
- dzil listdeps --missing | cpanm --notest
- dzil install --install-command "cpanm --notest ."
- cd ..
addons:
  apt:
    packages:
    - git
    - wget
    - file
    - build-essential
    - libssl-dev
    - libexpat1-dev
    - libdbd-mysql-perl
    - cpanminus
    - libz-dev
    - libdb-dev
perl:
- "5.30"
install:
- dzil authordeps --missing | cpanm --notest 
- dzil listdeps --missing | cpanm --notest
script:
- dzil install --install-command "cpanm --notest ."
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: java_launchers-${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    tags: true
